# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: NSPanel Lovelace UI Addon
version: "4.7.12"
slug: nspanel-lovelace-ui
description: NSPanel Lovelace UI Addon
services:
  - "mqtt:want"
homeassistant_api: true
url: "https://github.com/joBr99/nspanel-lovelace-ui/tree/main/nspanel-lovelace-ui"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/jobr99/{arch}-nspanel-lovelace-ui"
